#the database djdesweb must be created previously

services:
  djdesweb:
    restart: "no"
    build: ./djdesweb
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./djdesweb:/usr/src/app
    ports:
      - 127.0.0.1:${DEVELOP_DOCKER_DJANGO_API_FORWARDED_PORT}:8000
    env_file:
      - .env
      - .env.dev
    networks:
      - postgis_postgis

networks:
   postgis_postgis:
      driver: bridge
      external: true

